# File path configuration
data:
  dataset_path: './data/data.csv'  # Path to the dataset
  index_column: 0                    # Index column to use

# Columns configuration
columns:
  numerical_features:
    - Loan_Amount
    - Credit_Score
    - Annual_Income
    - Employment_Length
    - Debt-to-Income_Ratio
    - Number_of_Open_Accounts
    - Number_of_Past_Due_Payments
  nominal_features:
    - Loan_Purpose 
  loan_purpose_categories:
    - business
    - home improvement
    - medical expenses
    - debt consolidation
    - car
  target_column: Risk_Category

# Preprocessing configuration
preprocessing:
  impute_missing:
    categorical:
      - Risk_Category
      - Loan_Purpose
    numerical:
      - Loan_Amount
      - Credit_Score
      - Annual_Income
      - Employment_Length
      - Debt-to-Income_Ratio
      - Number_of_Open_Accounts
      - Number_of_Past_Due_Payments
  absolute_values:
    - Loan_Amount
    - Credit_Score
    - Annual_Income
    - Employment_Length
    - Debt-to-Income_Ratio
    - Number_of_Open_Accounts
    - Number_of_Past_Due_Payments
  drop_duplicates: true

# Training configuration
training:
  test_size: 0.2                     # Proportion of data to be used as validation/test
  val_size: 0.1                      # Proportion of data to be used as the validation set    
  random_state: 42                   # Random state for reproducibility

# Logistic Regression configuration
logistic_regression:
  C_values: [0.01, 0.1, 1, 10, 100]   # Regularization strength
  solver: 
    - liblinear
    - lbfgs
  penalties: 
    - l1
    - l2

# KNN configuration
knn:
  n_neighbors: 
    - 3
    - 5
    - 7
    - 9
    - 11
  weights: 
    - uniform
    - distance
  metrics: 
    - euclidean
    - manhattan

# Decision Tree configuration
decision_tree:
  max_depth: 
    - null
    - 5
    - 10
    - 15
    - 20
  min_samples_split: 
    - 2
    - 5
    - 10
  min_samples_leaf: 
    - 1
    - 2
    - 4
  criterion: 
    - gini
    - entropy

# Evaluation configuration
evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1_score
    - roc_auc
